services:
  services:
    image: postgres 
    container_name: postgres_d_compose
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: control
    ports:
      - "5432:5432"